apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
      "smtp_smarthost": "smtp.qq.com:465" 
      "smtp_from": "zhuchance@126.com" 
      "smtp_auth_username": "zhuchance@126.com"
      "smtp_auth_password": "wj0730"
      "smtp_require_tls": "false" 
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "critical"
      "target_match_re":
        "severity": "warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "warning"
      "target_match_re":
        "severity": "info"
    "receivers":
    - "name": "Default"
    - "name": "Watchdog"
    - "name": "Critical"
    - "email_configs": 
      - "to": "18120100305@189.cn"
        "headers": "{ Subject: "[WARN] 告警来啦" }" 
    "route":
      "group_by":
      - "namespace"
      "group_interval"