apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-controller-manager
  labels:
    k8s-app: kube-controller-manager
spec:
  # 使用了selector不需要指定 endpoints
  selector:
    component: kube-controller-manager
  ports:
  - name: https-metrics
    port: 10252
    targetPort: 10252
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-controller-manager
  name: kube-controller-manager
  namespace: kube-system
subsets:
  - addresses:
      - ip: 172.29.0.2
      - ip: 172.29.0.3
    ports:
    - name: https-metrics
      port: 10252
      protocol: TCP
####
#Open External  Port
#ExecStart=/opt/kube/bin/kube-controller-manager \
#  --address=0.0.0.0 \