apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: alertmanager-main
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9093
    targetPort: web
  # type: NodePort
  type: LoadBalancer
    # nodePort: 39090   
  selector:
    alertmanager: main
    app: alertmanager
  sessionAffinity: ClientIP
