apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  # type: NodePort
  type: LoadBalancer
  externalIPs:
    - 172.29.18.3
    # nodePort: 39090   
  selector:
    app: grafana
