apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  # type: NodePort
  type: LoadBalancer
#  ClusterIP: 172.29.138.133
  externalIPs:
    - 172.29.18.2
    # nodePort: 39090    
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: ClientIP
