apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 10m
      receiver: 'webhook'
    receivers:
    - name: 'webhook-wechat'
      webhook_configs:
      - url: 'http://alertwx-svc/'
        send_resolved: true
    - name: 'webhook'
      webhook_configs:
      - url: 'http://[prometheus-alert-center.monitoring.svc.cluster.local]:8080/prometheus/router?wxurl=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ae93ff29-f182-4c89-9719-0411354f112d'
        send_resolved: true
    - name: 'webhook-ccwx'
      webhook_configs:
      - url: 'http://[prometheus-alert-center.monitoring.svc.cluster.local]:8080/prometheus/router?fsurl=https://wechat.xiaocaicai.com/send_message/cgi-bin/webhook/19502934886@chatroom'
        send_resolved: true
    - name: 'webhook-ccwx-tes'
      webhook_configs:
                                      # /prometheusalert?type=fs&tpl=prometheus-fs&fsurl=
      - url: 'http://172.29.0.2:18080/prometheusalert?type=fs&tpl=prometheus-fs&fsurl=https://wechat.xiaocaicai.com/send_message'
      # - url: 'http://172.29.0.2:18080/prometheus/router?fsurl=https://wechat.xiaocaicai.com/send_message/'
        send_resolved: true
type: Opaque