apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 10m
      receiver: 'webhook'
    receivers:
    - name: 'webhook-ccwx'
      webhook_configs:
      - url: 'http://[prometheus-alert-center.monitoring.svc.cluster.local]:8080/prometheus/router?fsurl=https://wechat.xiaocaicai.com/send_message/cgi-bin/webhook/19502934886@chatroom'
        send_resolved: true
    - name: 'webhook-ccwx-tes'
      webhook_configs:
      'http://[prometheus-alert-center.wechart.svc.cluster.local]:8080/prometheusalert?type=dd&tpl=prometheus-dd&ddurl=http://wechart-service.wechart.svc.cluster.local:8081/sendTextMsg'
        send_resolved: true
        
type: Opaque8